Script serves two purposes:
Curates data for 3d grader
Builds models for grading EiPE answers (Data is 3D)

In [39]:
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.mixture import GaussianMixture
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold


from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier


import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import ConfusionMatrixDisplay


nltk.download('punkt')
nltk.download('words')

from nltk.corpus import words




[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\chine\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\chine\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!


In [40]:
data_file = "sigcse_2024.csv"
alldata_df = pd.read_csv(data_file, encoding="utf-8")


In [41]:
alldata_df.head()

subset embedding_subset  embedding_index                          pl_qid  \
0     train            train               97  cdrd_exam1_manual/cdrd_exam1_1   
1  validate            train              113  cdrd_exam1_manual/cdrd_exam1_1   
2     train            train              138  cdrd_exam1_manual/cdrd_exam1_2   
3  validate            train              150                 cdrd_week5_exam   
4     train            train              228  cdrd_exam3_manual/cdrd_exam3_1   

                                                 qid  \
0                print_found_if_three_numbers_unique   
1                print_items_out_smaller_then_larger   
2                           computes_average_of_list   
3                       does_list_have_value_above_y   
4  count how many times a given string appears in...   

                                                code  \
0  def f(x, y, z):\n    if x != y and x != z and ...   
1  def f(x, y):\n    if x < y:\n        print(x, ...   
2              def f(x):\n    return sum(x) / len(x)   
3  def f(x, y):\n    for val in x:\n        if va...   
4  def f(x, y):\n    k = 0\n    for e in x:\n    ...   

                                          assumption  \
0  Assume that the variables x, y, and z are inte...   
1    Assume that the variables x and y are integers.   
2  Assume that the variable x is a non-empty list...   
3  Assume that the variable x is a list of intege...   
4  Assume that variable x is a list of strings an...   

                             example_correct_answers  \
0  ['Print the word found if all three numbers ar...   
1  ['prints two given numbers in numberical order...   
2  ['Returns the average value in a list', 'finds...   
3  ['Return True if at least one list element is ...   
4  ['Return a count of how many times a given str...   

                                            response      binary_annotators  \
0  the code checks if all arguments regarding var...      ['Austin', 'Max']   
1     prints two numbers ordered smallest to largest      ['Austin', 'Max']   
2                      returns the average of a list  ['Binglin', 'Rachel']   
3  returns whether the first value in a list is g...            ['Binglin']   
4  return the number of times in which the string...  ['Binglin', 'Rachel']   

   ...  chinny_una  chinny_c  chinny_hl  binglin_una  binglin_c  binglin_hl  \
0  ...           0         0        0.0            0          0           0   
1  ...           1         1        1.0            1          1           1   
2  ...           1         1        1.0            1          1           1   
3  ...           1         0        1.0            1          0           1   
4  ...           1         1        0.0            1          1           1   

   una  c  hl  3d_resolution  
0    1  0   0      reconcile  
1    0  1   1      reconcile  
2    1  1   1      reconcile  
3    1  0   1      reconcile  
4    1  1   1      reconcile  

[5 rows x 24 columns]

In [42]:
def display_class_dist(given_df):
    '''
    Display the distribution of data for each qid. There are 8 possible bins.
    '''
    classes =  {(0,0,0): 0, (0,0,1):0, (0,1,0):0, (0,1,1):0, 
                (1,0,0):0, (1,1,0):0, (1,0,1):0, (1,1,1):0}
    
    ordering = [(0,0,0), (0,0,1), (0,1,0), (0,1,1), (1,0,0), (1,1,0), (1,0,1), (1,1,1)]
    
    print("3D groupings = (unambig, correct, highlevel)\n\n")
    print("3D label,  Freq. (Num Times Occur)")
    
    numrowsdata = 0
    
    for index, row in given_df.iterrows():
        
        cur_unambig = row["una"]
        cur_correct = row["c"]
        cur_hl      = row["hl"]
        
        classes[(cur_unambig, cur_correct, cur_hl)] += 1
        numrowsdata += 1
    
    for curbin in ordering:
        curbincount = classes[curbin] #get the number of occurrences of a particular labeling configuration within the data
        print("{}  {:>5.2f}% ({})".format(curbin, round(100*curbincount/numrowsdata, 2), curbincount)) #print group name, group freq and raw count of group occur.


    
def qid_dist(given_df):
    """
    Show how frequently each qid occured in the data
    """
    pass

In [43]:
filter1 = alldata_df[alldata_df["subset"] == "train"]
print(filter1.shape)
filter2= filter1[filter1["qid"] == "computes_average_of_list"]
print(filter2.shape)
display_class_dist(filter2)

display_class_dist(alldata_df[alldata_df["qid"] == "computes_average_of_list"])

(1832, 24)
(72, 24)
3D groupings = (unambig, correct, highlevel)


3D label,  Freq. (Num Times Occur)
(0, 0, 0)   0.00% (0)
(0, 0, 1)   0.00% (0)
(0, 1, 0)   0.00% (0)
(0, 1, 1)   8.33% (6)
(1, 0, 0)   0.00% (0)
(1, 1, 0)  44.44% (32)
(1, 0, 1)   0.00% (0)
(1, 1, 1)  47.22% (34)
3D groupings = (unambig, correct, highlevel)


3D label,  Freq. (Num Times Occur)
(0, 0, 0)   0.00% (0)
(0, 0, 1)   0.00% (0)
(0, 1, 0)   0.00% (0)
(0, 1, 1)   9.17% (11)
(1, 0, 0)   0.83% (1)
(1, 1, 0)  42.50% (51)
(1, 0, 1)   0.00% (0)
(1, 1, 1)  47.50% (57)


In [44]:
#distribution of all the data, even those tuples that were manually reconciled.
display_class_dist(alldata_df)

3D groupings = (unambig, correct, highlevel)


3D label,  Freq. (Num Times Occur)
(0, 0, 0)   6.01% (184)
(0, 0, 1)  13.38% (410)
(0, 1, 0)   1.44% (44)
(0, 1, 1)   9.76% (299)
(1, 0, 0)   4.44% (136)
(1, 1, 0)   6.59% (202)
(1, 0, 1)  20.30% (622)
(1, 1, 1)  38.09% (1167)


In [45]:
stemmer = PorterStemmer()

def preprocess_text(studentresponse):    
    words = word_tokenize(studentresponse)
    stemmed_words = [stemmer.stem(word) for word in words]
    lower_words= [word.lower() for word in stemmed_words] #convert to lowercase
    stemmed_words = lower_words
    regular_alpha = [] 
    for word in stemmed_words:
        if word.isalnum():  #remove any word that isn't an alphabet or a number.
            regular_alpha.append(word)
    stemmed_words = regular_alpha
    
    #TODO - need to handle stop words by passing in my own list. (related to tf-idf weighting)
    
    return " ".join(stemmed_words)

In [46]:
#distance metrics
#TODO: consider a few metrics


def cosine_similarity(x, y):
    #compute the cosine similarity of two vectors

    return sklearn.metrics.pairwise.cosine_similarity(x, y).item()     #using .item() to get value as a scalar
    
def distance_from_golden(golden, given_ans, dist_func):
    #compute a distance metric for the distance between a given answer and the golden answer
    distance = dist_func(golden, given_ans)
    if distance == None:
        return float("inf")
    else:
        return distance

In [47]:
def plot_confusion_matrix(confusion_matrix, what_to_predict, accuracy ):
        '''
        Function to help with plotting a confusion matrix
        '''
        plt.figure(figsize=(9,9))
        sns.heatmap(confusion_matrix, annot=True, fmt=".3f", linewidths=.5, square = True, cmap = 'Blues_r');
        plt.ylabel('Actual label');
        plt.xlabel('Predicted label');
        all_sample_title = 'Accuracy Score for {thingtopredict}: {accscore:.2f}'.format(thingtopredict = what_to_predict,
                                                                                    accscore = accuracy)
        plt.title(all_sample_title, size = 15);
        

def process_raw_features(given_df, pct_for_train = 0.8):
    """
    Process the raw text and get it ready to be trained
    Return processed text as a list of lists, where each list is one student response or one row of data
    """
    
    numsamples = 0
    limit = int(pct_for_train * len(given_df["response"]))
    processed_studentanswers = []
    
    for studentanswer in given_df["response"]:
        
        processed_answer = preprocess_text(studentanswer)
        processed_studentanswers.append(processed_answer)
        numsamples += 1
        
        if numsamples == limit:
            break
    return processed_studentanswers


def add_similarity_vector(golden_answers, students_responses_as_vec, curvec_fitter):
    """
    Create a column vector that represents the distance of a given student answer from the golden answer
    """
    golden_answers_vectors = curvec_fitter.transform(golden_answers).toarray()
    
    sim_vector = []
    
    #print("Shape of all student vectors = {}".format(students_responses_as_vec.shape))
    #print("Shape of golden_answers_vectors = {}".format(golden_answers_vectors.shape))
    
    for curstudent_vec in students_responses_as_vec:
        
        #print("Shape single student vector = {}".format(curstudent_vec.shape))
        best_similar = float("-inf") #ranges from 0 to 1 (1 meaning very similar or identical)
        
        for single_golden_answer_vec in golden_answers_vectors:
            #print("Shape single golden answer vector = {}".format(single_golden_answer_vec.shape))
            #cur_distance = distance_from_golden(single_golden_answer_vec, curstudent_vec, cosine_similarity)
            #compute distance. reshape the data into row vectors
            
            parta = single_golden_answer_vec.reshape(1,-1)
            partb = curstudent_vec.reshape(1,-1)
            
            #print("After reshaping, current size = {} for golden answer and  {} for student vector".format(parta.shape, partb.shape))
            
            cur_distance = cosine_similarity(parta, partb)
            best_similar = max(best_similar, cur_distance)
            
        sim_vector.append(best_similar)
    
    sim_vector = np.array(sim_vector)
    sim_vector = sim_vector.reshape(-1,1) #need to convert into a proper column vector
    return sim_vector


def train_model_and_validate(given_train_df, given_validate_df, golden_answers = [], qname = ""):
    
    ydims =  ["una", "c", "hl"]
    
    
    X_train_processed_text = process_raw_features(given_train_df, pct_for_train = 1)
 
    vectorizer = CountVectorizer(ngram_range = (2,2), min_df = 2)
    vec_fitter = vectorizer.fit(X_train_processed_text)    #fit only on training data to prevent overfit
    
    
    X_train = vec_fitter.transform(X_train_processed_text).toarray() #transform data into vectors and convert it to array    
    y_train = given_train_df[ydims].to_numpy(dtype=int)
    
    X_validate_processed_text = process_raw_features(given_validate_df, pct_for_train = 1)
    X_validate = vec_fitter.transform(X_validate_processed_text).toarray()  #use the previously fitted vectorizer to maintain shape
    y_validate = given_validate_df[ydims].to_numpy(dtype=int)
    
    if len(golden_answers) > 0:
    
        distance_from_golden_vector_trainset = add_similarity_vector(golden_answers, X_train, vec_fitter)
        distance_from_golden_vector_validationset  = add_similarity_vector(golden_answers, X_validate, vec_fitter)
        
        print("Original X data shape = {}, golden_answer_shape = {}".format(X_train.shape,
                                                                           distance_from_golden_vector_trainset.shape))
        
        X_train = np.append(X_train, distance_from_golden_vector_trainset, axis = 1)
        X_validate = np.append(X_validate, distance_from_golden_vector_validationset, axis = 1)
        
#         X_train.append(distance_from_golden_vector_trainset, axis = 1)
#         X_validate.append(distance_from_golden_vector_validationset, axis = 1)
    
    
    
 
        
    labels_order = ["Unambig", "Correct", "High level"]
    accuracy_l = []
    
    

    for i in range(3):
        model = LogisticRegression(random_state = 0)
        
        num_classes = list(np.unique(y_train[:,i])) #check number of classes in data. should be two
        print("We have {} classes".format(len(num_classes)))
        if len(num_classes) == 1: #change the last y in the tuple to force training to go through - otherwise, throwing error
            y_train[-1, i] = 0 if y_train[-1, i] == 1 else 0
        
        model = model.fit(X_train, y_train[:,i]) #train only one column at a time
        
        binary_y_predictions = model.predict(X_validate)
        
        #use the withheld set for testing the model
        print("{} Log reg. model performance on the withheld test set:\n\n".format(labels_order[i]))
        
        #for the y_test data (the true labels for column i), check if the predictions match
        dim_accuracy = metrics.accuracy_score(y_validate[:, i], binary_y_predictions)
        print("Accuracy is = ", dim_accuracy)
        accuracy_l.append(dim_accuracy)
        #print(metrics.classification_report(y_test, binary_y_predictions))


        print("\n\nConfusion Matrix:")
        
        confusion_matrix = metrics.confusion_matrix(y_validate[:, i],binary_y_predictions, normalize="true")
        print(confusion_matrix)
        
        #uncomment next line to print the confusion matrix
        #plot_confusion_matrix(confusion_matrix, labels_order[i] + qname,  dim_accuracy)
        print("\n\n")
        
    return accuracy_l  #accuracy for the three dimensions for a given problem


In [48]:
#for each question, create the input representation
#train various models, bigrams, bigrams + distance_from_golden, report on performance

train_pct = 1 #num from 0 to 1. currently 1 because want to train with 100% of train dataset
qids_accuracy = []

train_df = alldata_df[alldata_df["subset"] == "train"]       #select only training rows
validate_df = alldata_df[alldata_df["subset"] == "validate"] #only validation row

#alldata_df[alldata_df["subset"] == "train" & alldata_df["qid"] == "computes average of list"]


for cur_qid in alldata_df["qid"].unique().tolist():
    
    cur_question_training_df = train_df[train_df["qid"] == cur_qid]
    cur_question_validation_df = validate_df[validate_df["qid"] == cur_qid]
    
    print("QID = \'{}.\'".format(cur_qid))
    qname_formatted = ": " + cur_qid #format cur_qid name so it looks nice when printed with other function
    
    cur_qid_accuracy = train_model_and_validate(cur_question_training_df, cur_question_validation_df, qname = qname_formatted)
    
    qids_accuracy.append(cur_qid_accuracy)
    print("\n\n")


  

QID = 'print_found_if_three_numbers_unique.'
We have 2 classes
Unambig Log reg. model performance on the withheld test set:


Accuracy is =  0.5625


Confusion Matrix:
[[0.23529412 0.76470588]
 [0.06666667 0.93333333]]



We have 2 classes
Correct Log reg. model performance on the withheld test set:


Accuracy is =  0.8125


Confusion Matrix:
[[0.33333333 0.66666667]
 [0.07692308 0.92307692]]



We have 2 classes
High level Log reg. model performance on the withheld test set:


Accuracy is =  0.875


Confusion Matrix:
[[0.2 0.8]
 [0.  1. ]]






QID = 'print_items_out_smaller_then_larger.'
We have 2 classes
Unambig Log reg. model performance on the withheld test set:


Accuracy is =  0.8144329896907216


Confusion Matrix:
[[0.42857143 0.57142857]
 [0.02898551 0.97101449]]



We have 2 classes
Correct Log reg. model performance on the withheld test set:


Accuracy is =  0.8144329896907216


Confusion Matrix:
[[0.53846154 0.46153846]
 [0.08450704 0.91549296]]



We have 2 classes
High l

Unambig Log reg. model performance on the withheld test set:


Accuracy is =  0.5454545454545454


Confusion Matrix:
[[0.33333333 0.66666667]
 [0.30769231 0.69230769]]



We have 2 classes
Correct Log reg. model performance on the withheld test set:


Accuracy is =  0.9090909090909091


Confusion Matrix:
[[0.91666667 0.08333333]
 [0.1        0.9       ]]



We have 2 classes
High level Log reg. model performance on the withheld test set:


Accuracy is =  0.7727272727272727


Confusion Matrix:
[[0.57142857 0.42857143]
 [0.13333333 0.86666667]]






QID = 'absolute_value.'
We have 2 classes
Unambig Log reg. model performance on the withheld test set:


Accuracy is =  0.6


Confusion Matrix:
[[0.375      0.625     ]
 [0.14285714 0.85714286]]



We have 2 classes
Correct Log reg. model performance on the withheld test set:


Accuracy is =  0.7333333333333333


Confusion Matrix:
[[1.         0.        ]
 [0.44444444 0.55555556]]



We have 2 classes
High level Log reg. model performance on

In [49]:
#2nd model which incorporates the distance to the closest golden answer 

import ast
        

for cur_qid in alldata_df["qid"].unique().tolist():
    
        
    cur_question_training_df = train_df[train_df["qid"] == cur_qid]
    cur_question_validation_df = validate_df[validate_df["qid"] == cur_qid]
    
    print("QID = \'{}.\'".format(cur_qid))
    qname_formatted = ": " + cur_qid #format cur_qid name so it looks nice when printed with other function
    
    q_goldenanswers = cur_question_training_df["example_correct_answers"].iloc[0]
    q_goldenanswers = ast.literal_eval(q_goldenanswers)
    
    if type(q_goldenanswers) != list:
        print("Had to convert to list")
        q_goldenanswers = [q_goldenanswers]

    
    cur_qid_accuracy = train_model_and_validate(cur_question_training_df, cur_question_validation_df, 
                                                qname = qname_formatted, golden_answers = q_goldenanswers)
    
    qids_accuracy.append(cur_qid_accuracy)
    print("\n\n")


QID = 'print_found_if_three_numbers_unique.'
Original X data shape = (96, 116), golden_answer_shape = (96, 1)
We have 2 classes
Unambig Log reg. model performance on the withheld test set:


Accuracy is =  0.5625


Confusion Matrix:
[[0.23529412 0.76470588]
 [0.06666667 0.93333333]]



We have 2 classes
Correct Log reg. model performance on the withheld test set:


Accuracy is =  0.8125


Confusion Matrix:
[[0.33333333 0.66666667]
 [0.07692308 0.92307692]]



We have 2 classes
High level Log reg. model performance on the withheld test set:


Accuracy is =  0.875


Confusion Matrix:
[[0.2 0.8]
 [0.  1. ]]






QID = 'print_items_out_smaller_then_larger.'
Original X data shape = (291, 351), golden_answer_shape = (291, 1)
We have 2 classes
Unambig Log reg. model performance on the withheld test set:


Accuracy is =  0.8144329896907216


Confusion Matrix:
[[0.42857143 0.57142857]
 [0.02898551 0.97101449]]



We have 2 classes
Correct Log reg. model performance on the withheld test set:





Accuracy is =  0.7142857142857143


Confusion Matrix:
[[0.         1.        ]
 [0.09090909 0.90909091]]



We have 2 classes
Correct Log reg. model performance on the withheld test set:


Accuracy is =  0.6428571428571429


Confusion Matrix:
[[0.2        0.8       ]
 [0.11111111 0.88888889]]



We have 2 classes
High level Log reg. model performance on the withheld test set:


Accuracy is =  0.9285714285714286


Confusion Matrix:
[[0. 1.]
 [0. 1.]]








In [50]:
#show the accuracy of the classifier for each column across all data



qids_accuracy = np.array(qids_accuracy)
print("Averaging results for all qids in each of the respective dimensions\n")

avg_unambig_accuracy = np.mean(qids_accuracy[:, 0])
print("Avg accuracy for Unambig: {:.2f}".format(avg_unambig_accuracy))


avg_corr_accuracy = np.mean(qids_accuracy[:, 1])
print("Avg accuracy for Correct column: {:.2f}".format(avg_corr_accuracy))



avg_highlvl_accuracy = np.mean(qids_accuracy[:, 2])
print("Avg accuracy for High-level column: {:.2f}\n\n".format(avg_highlvl_accuracy))


avg_classifier_perf_overall = np.mean(qids_accuracy)
print("Average results across all dimensions for all qids: {:.2f}".format(avg_classifier_perf_overall))

Averaging results for all qids in each of the respective dimensions

Avg accuracy for Unambig: 0.73
Avg accuracy for Correct column: 0.81
Avg accuracy for High-level column: 0.87


Average results across all dimensions for all qids: 0.80


In [51]:

def train_model_and_validate_specify_order(given_train_df, given_validate_df, golden_answers = [], given_dims_order = [], qname = ""):
    
    ydims = given_dims_order #["una", "c", "hl"]
    

    X_train_processed_text = process_raw_features(given_train_df, pct_for_train = 1)
 
    vectorizer = CountVectorizer(ngram_range = (2,2), min_df = 2)
    vec_fitter = vectorizer.fit(X_train_processed_text)    #fit only on training data to prevent overfit
    
    
    X_train = vec_fitter.transform(X_train_processed_text).toarray() #transform data into vectors and convert it to array    
    
    
    
    y_train = given_train_df[ydims].to_numpy(dtype=int)
    
    X_validate_processed_text = process_raw_features(given_validate_df, pct_for_train = 1)
    X_validate = vec_fitter.transform(X_validate_processed_text).toarray()  #use the previously fitted vectorizer to maintain shape
    y_validate = given_validate_df[ydims].to_numpy(dtype=int)
    
    if len(golden_answers) > 0:
    
        distance_from_golden_vector_trainset = add_similarity_vector(golden_answers, X_train, vec_fitter)
        distance_from_golden_vector_validationset  = add_similarity_vector(golden_answers, X_validate, vec_fitter)
        
        print("Original X data shape = {}, golden_answer_shape = {}".format(X_train.shape,
                                                                           distance_from_golden_vector_trainset.shape))
        
        X_train = np.append(X_train, distance_from_golden_vector_trainset, axis = 1)
        X_validate = np.append(X_validate, distance_from_golden_vector_validationset, axis = 1)
        
#         X_train.append(distance_from_golden_vector_trainset, axis = 1)
#         X_validate.append(distance_from_golden_vector_validationset, axis = 1)
    
    
    
        
    labels_order = ["Unambig", "Correct", "High level"]
    accuracy_l = []
  
    
    col1name, col2name, col3name = given_dims_order #order of the y dimensions
    
    y_firstcol_train_vector = given_train_df[col1name].to_numpy(dtype=int) 
    y_secondcol_train_vector = given_train_df[col2name].to_numpy(dtype=int)
    y_thirdcol_train_vector = given_train_df[col3name].to_numpy(dtype=int)
    
    
    #potential
    
    firstdim_feedback_indices = []
    seconddim_feedback_indices = []
    thirddim_feedback_indices = []
    
    
    num_classes = list(np.unique(y_firstcol_train_vector)) #check number of classes in data. should be two
    if len(num_classes) == 1: #change the last y in the tuple to force training to go through - otherwise, throwing error
        y_firstcol_train_vector[-1] = 0 if y_firstcol_train_vector[-1] == 1 else 0

        
    model1 = LogisticRegression(random_state = 0)
    model1 = model1.fit(X_train, y_firstcol_train_vector) #train only one column at a time
    round1_y_predictions = model1.predict(X_train)
    
    
    for i in range(len(round1_y_predictions)):
        if round1_y_predictions[i] == 1: #no feedback needed for that dimension. feedback potentially for next dimension
            firstdim_feedback_indices.append(i)

    round2_X_train_input = []
    round2_y_train_input = []
    for cur_index in firstdim_feedback_indices:
        round2_X_train_input.append(X_train[cur_index, :])
        round2_y_train_input.append(y_secondcol_train_vector[cur_index])
    
    
    round2_X_train_input = np.array(round2_X_train_input)
    round2_y_train_input = np.array(round2_y_train_input)
    
        
    
    num_classes2 = list(np.unique(round2_y_train_input)) #check number of classes in data. should be two
    if len(num_classes2) == 1: #change the last y in the tuple to force training to go through - otherwise, throwing error
        round2_y_train_input[-1] = 0 if round2_y_train_input[-1] == 1 else 0

        
        
        
    model2 = LogisticRegression(random_state = 0)
    model2 = model2.fit(round2_X_train_input, round2_y_train_input)
    round2_y_predictions = model2.predict(round2_X_train_input)
    
    
    round3_X_train_input = []
    round3_y_train_input = []
    for i  in range(len(round2_y_predictions)):
        
        if round2_y_predictions[i] == 1: #no feedback needed for that dimension. feedback potentially needed for next dinmension
            
            round3_X_train_input.append(round2_X_train_input[i])
            round3_y_train_input.append(y_thirdcol_train_vector[i])
    
        
    num_classes3 = list(np.unique(round3_y_train_input)) #check number of classes in data. should be two
    if len(num_classes3) == 1: #change the last y in the tuple to force training to go through - otherwise, throwing error
        round3_y_train_input[-1] = 0 if round3_y_train_input[-1] == 1 else 0

        
    model3 = LogisticRegression(random_state = 0)
    model3 = model3.fit(round3_X_train_input, round3_y_train_input)
    round3_y_predictions = model3.predict(round3_X_train_input)
    
    classification_predictions = []
    
    print("input validation =", type(X_validate), " shape", X_validate.shape)
    classification_predictions = model1.predict(X_validate).reshape(-1,1)
    #print("model 1 predictions type = ", type(cola))
    classification_predictions = np.append(classification_predictions, model2.predict(X_validate).reshape(-1,1), axis = 1)
    classification_predictions = np.append(classification_predictions, model3.predict(X_validate).reshape(-1,1), axis = 1)
    
    
    
#     for given_response_vec in X_validate:
#         print("asking for prediction for = ", type(given_response_vec))
#         classifed = model1.predict(given_response_vec) + model2.predict(given_response_vec) + model3.predict(given_response_vec)
#         print("prediction should be list = ", type(classified))
#         classification_predictions.append(classified)
    
   #classification_predictions = np.array(classification_predictions)
    
    accuracy_l = []
    for i in range(3):
        dim_accuracy = metrics.accuracy_score(y_validate[:, i], classification_predictions[:,i])
        print("Accuracy is = ", dim_accuracy)
        accuracy_l.append(dim_accuracy)
        
        print("\n\nConfusion Matrix:")
        
        confusion_matrix = metrics.confusion_matrix(y_validate[:, i], classification_predictions[:,i], normalize="true")
        print(confusion_matrix)
        
        #uncomment next line to print the confusion matrix
        #plot_confusion_matrix(confusion_matrix, labels_order[i] + qname,  dim_accuracy)
        print("\n\n")
        
    return accuracy_l  #accuracy for the three dimensions for a given problem

In [59]:

import ast
best_order = None
best_order_acc = 0

for dims_order in [["una", "c", "hl"], ["una", "hl" , "c"], ["hl", "una", "c"], ["hl", "c", "una"], ["c", "hl", "una"], 
                   ["c", "una", "hl"]]:
    
        
        qids_accuracy = []
     
        print("--------------------------------------------------------------------------------------------------\n")
        print("Cur order = {}".format(dims_order))
        for cur_qid in alldata_df["qid"].unique().tolist():


            cur_question_training_df = train_df[train_df["qid"] == cur_qid]
            cur_question_validation_df = validate_df[validate_df["qid"] == cur_qid]

            print("QID = \'{}.\'".format(cur_qid))
            qname_formatted = ": " + cur_qid #format cur_qid name so it looks nice when printed with other function

            q_goldenanswers = cur_question_training_df["example_correct_answers"].iloc[0]
            q_goldenanswers = ast.literal_eval(q_goldenanswers)

            if type(q_goldenanswers) != list:
                print("Had to convert to list")
                q_goldenanswers = [q_goldenanswers]


            cur_qid_accuracy = train_model_and_validate_specify_order(cur_question_training_df, cur_question_validation_df, 
                                                        qname = qname_formatted, golden_answers = q_goldenanswers, 
                                                                      given_dims_order = dims_order)

            qids_accuracy.append(cur_qid_accuracy)
            print("\n\n")


        qids_accuracy = np.array(qids_accuracy)
        print("Averaging results for all qids in each of the respective dimensions\n")

        avg_unambig_accuracy = np.mean(qids_accuracy[:, 0])
        print("Avg accuracy for Unambig: {:.2f}".format(avg_unambig_accuracy))


        avg_corr_accuracy = np.mean(qids_accuracy[:, 1])
        print("Avg accuracy for Correct column: {:.2f}".format(avg_corr_accuracy))



        avg_highlvl_accuracy = np.mean(qids_accuracy[:, 2])
        print("Avg accuracy for High-level column: {:.2f}\n\n".format(avg_highlvl_accuracy))


        avg_classifier_perf_overall = np.mean(qids_accuracy)
        print("Average results across all dimensions for all qids: {:.2f}".format(avg_classifier_perf_overall))
    
        if best_order_acc < avg_classifier_perf_overall:
            best_order = dims_order
            best_order_acc = avg_classifier_perf_overall

--------------------------------------------------------------------------------------------------

Cur order = ['una', 'c', 'hl']
QID = 'print_found_if_three_numbers_unique.'
Original X data shape = (96, 116), golden_answer_shape = (96, 1)
input validation = <class 'numpy.ndarray'>  shape (32, 117)
Accuracy is =  0.5625


Confusion Matrix:
[[0.23529412 0.76470588]
 [0.06666667 0.93333333]]



Accuracy is =  0.78125


Confusion Matrix:
[[0.         1.        ]
 [0.03846154 0.96153846]]



Accuracy is =  0.84375


Confusion Matrix:
[[0. 1.]
 [0. 1.]]






QID = 'print_items_out_smaller_then_larger.'
Original X data shape = (291, 351), golden_answer_shape = (291, 1)
input validation = <class 'numpy.ndarray'>  shape (97, 352)
Accuracy is =  0.8144329896907216


Confusion Matrix:
[[0.42857143 0.57142857]
 [0.02898551 0.97101449]]



Accuracy is =  0.7938144329896907


Confusion Matrix:
[[0.38461538 0.61538462]
 [0.05633803 0.94366197]]



Accuracy is =  0.7010309278350515


Confusion Matr

Original X data shape = (291, 351), golden_answer_shape = (291, 1)
input validation = <class 'numpy.ndarray'>  shape (97, 352)
Accuracy is =  0.8144329896907216


Confusion Matrix:
[[0.42857143 0.57142857]
 [0.02898551 0.97101449]]



Accuracy is =  0.9072164948453608


Confusion Matrix:
[[0.82142857 0.17857143]
 [0.05797101 0.94202899]]



Accuracy is =  0.6701030927835051


Confusion Matrix:
[[0.03846154 0.96153846]
 [0.09859155 0.90140845]]






QID = 'computes_average_of_list.'
Original X data shape = (72, 59), golden_answer_shape = (72, 1)
input validation = <class 'numpy.ndarray'>  shape (24, 60)
Accuracy is =  0.9166666666666666


Confusion Matrix:
[[0. 1.]
 [0. 1.]]



Accuracy is =  0.9583333333333334


Confusion Matrix:
[[0.9 0.1]
 [0.  1. ]]



Accuracy is =  0.9583333333333334


Confusion Matrix:
[[0. 1.]
 [0. 1.]]






QID = 'does_list_have_value_above_y.'
Original X data shape = (45, 69), golden_answer_shape = (45, 1)
input validation = <class 'numpy.ndarray'>  shape (1

input validation = <class 'numpy.ndarray'>  shape (24, 91)
Accuracy is =  0.9166666666666666


Confusion Matrix:
[[0.33333333 0.66666667]
 [0.         1.        ]]



Accuracy is =  0.75


Confusion Matrix:
[[0.33333333 0.66666667]
 [0.11111111 0.88888889]]



Accuracy is =  0.7083333333333334


Confusion Matrix:
[[1. 0.]
 [1. 0.]]






QID = 'count how many numbers in a list are multiples of another number.'
Original X data shape = (101, 100), golden_answer_shape = (101, 1)
input validation = <class 'numpy.ndarray'>  shape (34, 101)
Accuracy is =  0.8823529411764706


Confusion Matrix:
[[0.75 0.25]
 [0.1  0.9 ]]



Accuracy is =  0.7647058823529411


Confusion Matrix:
[[0. 1.]
 [0. 1.]]



Accuracy is =  0.6176470588235294


Confusion Matrix:
[[0. 1.]
 [0. 1.]]






QID = 'a33_replace_all_ys_with_zs.'
Original X data shape = (161, 240), golden_answer_shape = (161, 1)
input validation = <class 'numpy.ndarray'>  shape (54, 241)
Accuracy is =  0.8888888888888888


Confusion Matrix:
[[0

input validation = <class 'numpy.ndarray'>  shape (54, 241)
Accuracy is =  0.8888888888888888


Confusion Matrix:
[[0.33333333 0.66666667]
 [0.         1.        ]]



Accuracy is =  0.8518518518518519


Confusion Matrix:
[[0.71428571 0.28571429]
 [0.06060606 0.93939394]]



Accuracy is =  0.5555555555555556


Confusion Matrix:
[[0.84       0.16      ]
 [0.68965517 0.31034483]]






QID = 'split a csv string and return the nth word.'
Original X data shape = (91, 90), golden_answer_shape = (91, 1)
input validation = <class 'numpy.ndarray'>  shape (30, 91)
Accuracy is =  0.9333333333333333


Confusion Matrix:
[[0. 1.]
 [0. 1.]]



Accuracy is =  0.8


Confusion Matrix:
[[0.94117647 0.05882353]
 [0.38461538 0.61538462]]



Accuracy is =  0.7666666666666667


Confusion Matrix:
[[0.66666667 0.33333333]
 [0.20833333 0.79166667]]






QID = 'return the location of an element if it is in the list.'
Original X data shape = (189, 188), golden_answer_shape = (189, 1)
input validation = <class '

input validation = <class 'numpy.ndarray'>  shape (63, 189)
Accuracy is =  0.8253968253968254


Confusion Matrix:
[[0.83783784 0.16216216]
 [0.19230769 0.80769231]]



Accuracy is =  0.9841269841269841


Confusion Matrix:
[[0. 1.]
 [0. 1.]]



Accuracy is =  0.746031746031746


Confusion Matrix:
[[0.         1.        ]
 [0.04081633 0.95918367]]






QID = 'list_copy_up_to_positive.'
Original X data shape = (57, 90), golden_answer_shape = (57, 1)
input validation = <class 'numpy.ndarray'>  shape (19, 91)
Accuracy is =  1.0


Confusion Matrix:
[[1. 0.]
 [0. 1.]]



Accuracy is =  0.8421052631578947


Confusion Matrix:
[[0. 1.]
 [0. 1.]]



Accuracy is =  0.631578947368421


Confusion Matrix:
[[0.         1.        ]
 [0.07692308 0.92307692]]






QID = 'find_largest_number_in_file.'
Original X data shape = (208, 188), golden_answer_shape = (208, 1)
input validation = <class 'numpy.ndarray'>  shape (69, 189)
Accuracy is =  0.9420289855072463


Confusion Matrix:
[[0.93548387 0.06451613]

input validation = <class 'numpy.ndarray'>  shape (69, 189)
Accuracy is =  0.9420289855072463


Confusion Matrix:
[[0.93548387 0.06451613]
 [0.05263158 0.94736842]]



Accuracy is =  0.8260869565217391


Confusion Matrix:
[[0. 1.]
 [0. 1.]]



Accuracy is =  0.9130434782608695


Confusion Matrix:
[[0.       1.      ]
 [0.015625 0.984375]]






QID = 'swaps_first_and_last.'
Original X data shape = (137, 127), golden_answer_shape = (137, 1)
input validation = <class 'numpy.ndarray'>  shape (46, 128)
Accuracy is =  0.782608695652174


Confusion Matrix:
[[0.85714286 0.14285714]
 [0.33333333 0.66666667]]



Accuracy is =  0.7391304347826086


Confusion Matrix:
[[0. 1.]
 [0. 1.]]



Accuracy is =  0.6521739130434783


Confusion Matrix:
[[0.72222222 0.27777778]
 [0.39285714 0.60714286]]






QID = 'return whether strings start with the same letter.'
Original X data shape = (85, 133), golden_answer_shape = (85, 1)
input validation = <class 'numpy.ndarray'>  shape (28, 134)
Accuracy is =  0.5

In [58]:
print("Best order is {}  with accuracy of {}".format(best_order, best_order_acc))

Best order is ['c', 'una', 'hl']  with accuracy of 0.7698478389227691


In [ ]:
a = np.array([15, 6, 7]).reshape(1,-1)
b = np.array([30, 12, 14]).reshape(1,-1)

cosine_similarity(a,b)

In [ ]:
confusion_matrix = metrics.confusion_matrix([1], [2], normalize="true")

In [ ]:
print(confusion_matrix)

In [ ]:
print(metrics.classification_report([2,3], [2,4]))